package com.example.util

enum class AppLanguage(val code: String, val displayName: String, val flagEmoji: String) {
    MYANMAR("my", "မြန်မာ", "🇲🇲"),
    ENGLISH("en", "English", "🇬🇧")
}

data class AppStrings(
    val appTitle: String = "Myo Min Khant",
    val appSubtitle: String,
    val tabRecipes: String,
    val tabCategories: String,
    val tabAddRecipe: String,
    val tabAiChef: String,
    val searchPlaceholder: String,
    val tabAll: String,
    val tabFavorites: String,
    val emptyTitle: String,
    val emptySubtitle: String,
    val btnAddNew: String,
    val btnCreateAi: String,
    val btnClearAll: String,
    val confirmClearTitle: String,
    val confirmClearText: String,
    val btnConfirmClear: String,
    val btnCancel: String,
    val minsUnit: String,
    val servingsUnit: String,
    val stepsUnit: String,
    val videoBadge: String,
    val btnWatchVideo: String,
    val btnAiAdvice: String,
    val ingredientsTitle: String,
    val stepsTitle: String,
    val notesTitle: String,
    val timerBtn: String,
    val prepTimeLabel: String,
    val cookTimeLabel: String,
    val servingsLabel: String,
    val btnResetChecklist: String,
    val checklistHint: String,
    val editRecipeTitle: String,
    val newRecipeTitle: String,
    val inputTitleLabel: String,
    val inputTitlePlaceholder: String,
    val categoryLabel: String,
    val categoryInputLabel: String,
    val inputDescLabel: String,
    val inputDescPlaceholder: String,
    val photosVideosTitle: String,
    val photoLabel: String,
    val btnPickPhoto: String,
    val videoUrlLabel: String,
    val btnAddIngredient: String,
    val btnAddStep: String,
    val ingredientNamePlaceholder: String,
    val ingredientAmountPlaceholder: String,
    val ingredientUnitPlaceholder: String,
    val stepDescPlaceholder: String,
    val stepTimerLabel: String,
    val notesPlaceholder: String,
    val btnSaveRecipe: String,
    val aiDraftHint: String,
    val btnUseAi: String,
    val aiChefTitle: String,
    val aiChefSubtitle: String,
    val aiTabCreate: String,
    val aiTabChat: String,
    val pantryTitle: String,
    val pantrySubtitle: String,
    val otherIngredientsLabel: String,
    val btnGenerateRecipe: String,
    val btnSaveAiRecipe: String,
    val askChefPlaceholder: String,
    val defaultChefGreeting: String,
    val categoriesTitle: String,
    val totalRecipesPrefix: String,
    val catCurry: String,
    val catSoup: String,
    val catSalad: String,
    val catFried: String,
    val catDessert: String,
    val catBreakfast: String,
    val catBeverage: String,
    val catSnacks: String,
    val catAll: String
)

object Localization {
    val Myanmar = AppStrings(
        appSubtitle = "ဟင်းချက်နည်း မှတ်စုများ",
        tabRecipes = "မှတ်စုများ",
        tabCategories = "အမျိုးအစား",
        tabAddRecipe = "အသစ်ထည့်ရန်",
        tabAiChef = "AI စားဖိုမှူး",
        searchPlaceholder = "ဟင်းအမည်၊ ပါဝင်ပစ္စည်းဖြင့် ရှာဖွေပါ...",
        tabAll = "အားလုံး",
        tabFavorites = "အကြိုက်ဆုံး",
        emptyTitle = "ဟင်းချက်နည်းမှတ်စု မရှိသေးပါ",
        emptySubtitle = "သင်ကိုယ်တိုင် ဟင်းချက်နည်းအသစ် ရေးသားနိုင်သလို AI စားဖိုမှူးကိုလည်း အကူအညီတောင်းနိုင်ပါသည်",
        btnAddNew = "အသစ်ထည့်မည်",
        btnCreateAi = "AI ဖြင့် ဖန်တီးမည်",
        btnClearAll = "ဒေတာအားလုံး ရှင်းလင်းမည်",
        confirmClearTitle = "ဒေတာအားလုံး ရှင်းလင်းရန် သေချာပါသလား?",
        confirmClearText = "ဟင်းချက်နည်း မှတ်စုများ အားလုံးကို ဖျက်ပစ်ပြီး အခွံအတိုင်း ပြန်လည် ထားရှိပါမည်။",
        btnConfirmClear = "ရှင်းလင်းမည်",
        btnCancel = "မလုပ်တော့ပါ",
        minsUnit = "မိနစ်",
        servingsUnit = "ယောက်စာ",
        stepsUnit = "ဆင့်",
        videoBadge = "ဗီဒီယို",
        btnWatchVideo = "ဗီဒီယို ကြည့်မည်",
        btnAiAdvice = "AI အကြံပြုချက်",
        ingredientsTitle = "ပါဝင်ပစ္စည်းများ",
        stepsTitle = "ချက်ပြုတ်ပုံ အဆင့်ဆင့်",
        notesTitle = "ကိုယ်ပိုင်မှတ်စုနှင့် လျှို့ဝှက်ချက်များ",
        timerBtn = "⏱ အချိန်မှတ်ရန်",
        prepTimeLabel = "ပြင်ဆင်ချိန်",
        cookTimeLabel = "ချက်ပြုတ်ချိန်",
        servingsLabel = "လူဦးရေ",
        btnResetChecklist = "ပြန်စစ်မည်",
        checklistHint = "ပြင်ဆင်ပြီးသော ပစ္စည်းများကို အမှန်ခြစ်၍ မှတ်သားထားနိုင်ပါသည်",
        editRecipeTitle = "ဟင်းချက်နည်း ပြင်ဆင်ရန်",
        newRecipeTitle = "ဟင်းချက်နည်းအသစ် မှတ်သားရန်",
        inputTitleLabel = "ဟင်းအမည် *",
        inputTitlePlaceholder = "ဥပမာ - ဝက်သားနီချက်",
        categoryLabel = "အမျိုးအစား",
        categoryInputLabel = "အမျိုးအစား အမည် (ရွေးချယ် သို့မဟုတ် စိတ်ကြိုက်ရေးပါ)",
        inputDescLabel = "ဟင်းအကျဉ်းချုပ် ဖော်ပြချက်",
        inputDescPlaceholder = "အရသာနှင့် အဓိကထူးခြားချက်ကို ရေးပါ...",
        photosVideosTitle = "ဓာတ်ပုံနှင့် ဗီဒီယို လင့်ခ်",
        photoLabel = "ဟင်းဓာတ်ပုံ",
        btnPickPhoto = "ပုံရွေးမည်",
        videoUrlLabel = "ချက်ပြုတ်နည်း ဗီဒီယို Link (YouTube/Web)",
        btnAddIngredient = "အသစ်ထည့်မည်",
        btnAddStep = "အဆင့်ထည့်မည်",
        ingredientNamePlaceholder = "ပစ္စည်းအမည် (ဥပမာ- ကြက်သား)",
        ingredientAmountPlaceholder = "ပမာဏ",
        ingredientUnitPlaceholder = "ယူနစ် (ဥပမာ- ပိဿာ)",
        stepDescPlaceholder = "ချက်ပြုတ်ပုံ ရှင်းလင်းချက် ရေးပါ...",
        stepTimerLabel = "အချိန် (မိနစ်):",
        notesPlaceholder = "ဟင်းချက်ရာတွင် သတိထားရမည့်အချက်များ၊ အရသာ ပိုကောင်းစေသည့် လျှို့ဝှက်ချက်များကို ရေးထားပါ...",
        btnSaveRecipe = "ဟင်းချက်နည်း မှတ်စုတွင် သိမ်းဆည်းမည်",
        aiDraftHint = "AI စားဖိုမှူးဖြင့် အလိုအလျောက် ရေးခိုင်းနိုင်ပါသည်",
        btnUseAi = "AI သုံးမည်",
        aiChefTitle = "AI စားဖိုမှူး",
        aiChefSubtitle = "Gemini ချက်ပြုတ်နည်း လက်ထောက်",
        aiTabCreate = "ချက်နည်းဖန်တီးရန်",
        aiTabChat = "စားဖိုမှူးနှင့် စကားပြောရန်",
        pantryTitle = "သင့်မီးဖိုချောင်ရှိ ပါဝင်ပစ္စည်းများကို ရွေးချယ်ပါ",
        pantrySubtitle = "လက်ကျန်ပစ္စည်းများကို အခြေခံ၍ AI မှ အရသာရှိသော မြန်မာဟင်းချက်နည်းကို တီထွင်ဖန်တီးပေးပါမည်။",
        otherIngredientsLabel = "အခြားပါဝင်ပစ္စည်းများ သို့မဟုတ် ဟင်းအမည်",
        btnGenerateRecipe = "ဟင်းချက်နည်း ဖန်တီးပေးပါ",
        btnSaveAiRecipe = "မှတ်စုထဲသို့ တိုက်ရိုက် သိမ်းဆည်းမည်",
        askChefPlaceholder = "ချက်ပြုတ်နည်း မေးမြန်းရန်...",
        defaultChefGreeting = "မင်္ဂလာပါ! ကျွန်တော် AI စားဖိုမှူးလက်ထောက်ပါ။ ဟင်းချက်နည်းများ၊ အစားထိုးပါဝင်ပစ္စည်းများ၊ သို့မဟုတ် လက်ကျန်ပစ္စည်းများနှင့် ဘာဟင်းချက်ရမလဲဆိုတာ မေးမြန်းနိုင်ပါတယ်ခင်ဗျာ။",
        categoriesTitle = "ဟင်းချက်နည်း အမျိုးအစားများ",
        totalRecipesPrefix = "စုစုပေါင်း ဟင်းချက်နည်း",
        catCurry = "ဟင်းလျာ",
        catSoup = "ဟင်းချို",
        catSalad = "အသုပ်",
        catFried = "အကြော်",
        catDessert = "အချိုပွဲ",
        catBreakfast = "မနက်စာ",
        catBeverage = "အဖျော်ယမကာ",
        catSnacks = "အဆာပြေ",
        catAll = "အားလုံး"
    )

    val English = AppStrings(
        appSubtitle = "Recipe Notebook",
        tabRecipes = "Recipes",
        tabCategories = "Categories",
        tabAddRecipe = "Add Recipe",
        tabAiChef = "AI Chef",
        searchPlaceholder = "Search recipe name, ingredients...",
        tabAll = "All",
        tabFavorites = "Favorites",
        emptyTitle = "No recipe notes yet",
        emptySubtitle = "Write your own recipe notes or ask AI Chef for assistance",
        btnAddNew = "Add New",
        btnCreateAi = "Create with AI",
        btnClearAll = "Clear All Data",
        confirmClearTitle = "Clear all data?",
        confirmClearText = "All recipe notes will be removed and reset to a clean blank state.",
        btnConfirmClear = "Clear",
        btnCancel = "Cancel",
        minsUnit = "mins",
        servingsUnit = "servings",
        stepsUnit = "steps",
        videoBadge = "Video",
        btnWatchVideo = "Watch Video",
        btnAiAdvice = "AI Advice",
        ingredientsTitle = "Ingredients",
        stepsTitle = "Cooking Instructions",
        notesTitle = "Chef Notes & Secrets",
        timerBtn = "⏱ Start Timer",
        prepTimeLabel = "Prep Time",
        cookTimeLabel = "Cook Time",
        servingsLabel = "Servings",
        btnResetChecklist = "Reset",
        checklistHint = "Check off ingredients as you prepare them",
        editRecipeTitle = "Edit Recipe",
        newRecipeTitle = "New Recipe Note",
        inputTitleLabel = "Recipe Title *",
        inputTitlePlaceholder = "e.g. Burmese Chicken Curry",
        categoryLabel = "Category",
        categoryInputLabel = "Category Name (Select or type custom)",
        inputDescLabel = "Short Description",
        inputDescPlaceholder = "Briefly describe the flavor and key highlights...",
        photosVideosTitle = "Photos & Video Link",
        photoLabel = "Recipe Photo",
        btnPickPhoto = "Choose Photo",
        videoUrlLabel = "Cooking Video URL (YouTube/Web)",
        btnAddIngredient = "Add Ingredient",
        btnAddStep = "Add Step",
        ingredientNamePlaceholder = "Item name (e.g. Chicken)",
        ingredientAmountPlaceholder = "Qty",
        ingredientUnitPlaceholder = "Unit (e.g. lbs / tbsp)",
        stepDescPlaceholder = "Explain this step in detail...",
        stepTimerLabel = "Timer (min):",
        notesPlaceholder = "Tips, cooking secrets, flavor tricks to remember...",
        btnSaveRecipe = "Save to Recipe Notebook",
        aiDraftHint = "Let AI Chef draft the recipe details automatically",
        btnUseAi = "Use AI",
        aiChefTitle = "AI Chef",
        aiChefSubtitle = "Gemini Culinary Assistant",
        aiTabCreate = "Generate Recipe",
        aiTabChat = "Ask Chef Chat",
        pantryTitle = "Select ingredients from your pantry",
        pantrySubtitle = "AI will formulate a delicious recipe based on what you have at home.",
        otherIngredientsLabel = "Other ingredients or dish name",
        btnGenerateRecipe = "Generate Recipe",
        btnSaveAiRecipe = "Save Directly to Notebook",
        askChefPlaceholder = "Ask about cooking, substitutes...",
        defaultChefGreeting = "Hello! I am your AI Chef Assistant. Ask me anything about recipes, ingredient substitutes, or what to cook with your ingredients!",
        categoriesTitle = "Recipe Categories",
        totalRecipesPrefix = "Total Recipes",
        catCurry = "Curry / Main",
        catSoup = "Soup",
        catSalad = "Salad",
        catFried = "Fried",
        catDessert = "Dessert",
        catBreakfast = "Breakfast",
        catBeverage = "Beverage",
        catSnacks = "Snacks",
        catAll = "All"
    )

    fun get(lang: AppLanguage): AppStrings = when (lang) {
        AppLanguage.MYANMAR -> Myanmar
        AppLanguage.ENGLISH -> English
    }
}
